### PR TITLE
fix CRLF in windows

### PR DESCRIPTION
**Pull request by suenchunhui**
@duemaster  can u see this this fixes the problem
based on https://www.vagrantup.com/docs/provisioning/shell.html

### CODE REVIEW

**Comment by suenchunhui** [comment]
https://stackoverflow.com/questions/28651275/windows-crlf-to-unix-lf-issues-in-vagrant too

**Comment by duemaster** [comment]
@suenchunhui It seems like the issue is still not resolved.
Still getting the following errors.
```
    default: ++ sudo chown vagrant -R /home/vagrant/workspace
    default: ++ su vagrant -c 'cd /home/vagrant/workspace ; npm run build_image'
    default:
    default: > sample-marbles-trade@0.1.0 build_image /home/vagrant/workspace
    default: > bash scripts/build_images.sh
    default: scripts/build_images.sh: line 2: $'\r': command not found
: No such file or directoryimages.sh: line 3: cd: /home/vagrant/workspace
    default: scripts/build_images.sh: line 4: $'\r': command not found
    default: unable to prepare context: path "/home/vagrant/workspace\r\r" not found
    default: unlink: cannot unlink '/home/vagrant/workspace'$'\r''/.dockerignore'$'\r': No such file or directory
    default: scripts/build_images.sh: line 9: $'\r': command not found
    default: invalid reference format
    default: invalid reference format
    default: invalid reference format
    default: invalid reference format
    default: invalid reference format
```

**Comment by suenchunhui** [comment]
@duemaster i switched to windows line ending.
by right the `binary` option will auto convert win to linux if needed.
can u try again if it works on windows?

**Comment by duemaster** [comment]
@suenchunhui 
Still facing the same error.

I tried changing the EOF for the build_image.sh and the vagrant image builds successfully. However, when trying to run the other `.sh` scripts in the vagrant VM, all are having the EOF issue.

Hence, it doesn't seem to be a problem with the line ending for the vagrant file, but instead, it seems to be an issue with the `.sh` files that are copied over the vagrant VM all having `CRLF` instead of `LF` EOF.

**Comment by duemaster** [comment]
Perhaps we can try cloning the repo directly in the VM instead?

**Comment by suenchunhui** [comment]
@duemaster  can help me test this one

**Comment by duemaster** [comment]
@suenchunhui 
It is working.

**Review by duemaster — APPROVED** [review]
Are we using 2 or 4 cores?

**Comment by suenchunhui** [comment]
> Are we using 2 or 4 cores?

should be 2

**Comment by duemaster** [comment]
@suenchunhui 
should be ok now.

**Pull request merged**
